import type { Meta, StoryObj } from '@storybook/react'
import SideNav from './SideNav'

/**
 * SideNavigation provides in-page navigation for case study pages. It uses
 * IntersectionObserver to track which section is currently visible and updates
 * the active state accordingly — a scrollspy pattern.
 *
 * ## Design rationale
 * IntersectionObserver was chosen over scroll event listeners because it's
 * declarative, performant, and doesn't require debouncing. The observer fires
 * only when a section enters or leaves the viewport, not on every scroll tick.
 *
 * The left border as the active indicator connects SideNavigation to a broader
 * cross-component visual language: CalloutCard, MetricCard, and PasswordGate all
 * use a red left or top accent bar to signal highlighted content. The active nav
 * item uses the same accent color on its left border, tying the navigation into
 * the same visual system.
 *
 * Hidden on tablet and mobile via the `.article-layout` grid collapse. The
 * component doesn't render a hamburger or dropdown alternative — on small screens,
 * in-page navigation is handled by native scroll.
 *
 * ## State model
 * - Default: `--text-muted`, weight 400, `--border` left border
 * - Hover: `--text-mid`, weight 500, `--border-mid` left border
 * - Active: `--accent`, weight 500, `--accent` left border
 *
 * ## Section label generation
 * Labels are auto-generated from section IDs by splitting on hyphens and
 * capitalizing each word. Examples:
 * - `overview` → "Overview"
 * - `user-research` → "User-Research" (hyphen preserved — IDs with hyphens
 *   should use underscores if a space is desired: `user_research`)
 *
 * ## Accessibility
 * Active items have `aria-current="true"` applied. Known gap: `aria-live` region
 * for the active state transition is not currently implemented.
 *
 * ## unlocked prop
 * When `unlocked` is false, the IntersectionObserver setup is deferred — the nav
 * renders but no item is active until the prop flips to true. Used when the case
 * study content is behind a PasswordGate. The `onUnlock` callback on PasswordGate
 * is the trigger that re-renders SideNavigation with `unlocked: true`.
 *
 * ## Tokens used
 * - Position: sticky, top 5rem
 * - Contents label: `--text-xs`, `--letter-spacing-lg`, uppercase, `--text-muted`, weight 500
 * - Link font size: `--text-base` (0.875rem / 14px)
 * - Default color: `--text-muted`
 * - Hover color: `--text-mid`
 * - Active color: `--accent`
 * - Default border: `--border`
 * - Hover border: `--border-mid`
 * - Active border: `--accent`
 * - Link padding: `--space-2` 0 `--space-2` `--space-3`
 * - Transition: color `--transition-base`, border-color `--transition-base`
 *
 * ## Usage
 * Used exclusively inside case study pages within the `.article-layout` grid.
 * The 200px left column holds the SideNavigation; the right column holds content.
 */
const meta: Meta<typeof SideNav> = {
  title: 'Core Components/Navigation/Side',
  tags: ['autodocs'],
  component: SideNav,
  argTypes: {
    sections: {
      control: 'object',
      description: 'Array of section IDs matching the id attributes of page sections. Labels are auto-generated by capitalizing each word split on hyphens.',
    },
    unlocked: {
      control: 'boolean',
      description: 'When false, IntersectionObserver setup is deferred. Used when content is behind PasswordGate. Flip to true after unlock to activate scrollspy.',
    },
  },
}

export default meta
type Story = StoryObj<typeof SideNav>

export const Default: Story = {
  args: {
    sections: ['overview', 'research', 'design', 'outcomes', 'reflections'],
    unlocked: true,
  },
}

export const MidSectionActive: Story = {
  name: 'Mid-Section Active',
  render: () => {
    const sections = ['overview', 'research', 'design', 'outcomes', 'reflections']
    const active = 'design'
    const getLinkStyle = (id: string): React.CSSProperties => ({
      fontSize: 'var(--font-size-base)',
      color: id === active ? 'var(--color-accent)' : 'var(--color-text-muted)',
      fontWeight: id === active ? 500 : 400,
      textDecoration: 'none',
      display: 'block',
      padding: 'var(--space-2) 0 var(--space-2) var(--space-3)',
      borderLeft: `2px solid ${id === active ? 'var(--color-accent)' : 'var(--color-border)'}`,
      lineHeight: 1.4,
    })
    return (
      <aside>
        <p style={{ fontSize: 'var(--font-size-xs)', letterSpacing: 'var(--letter-spacing-lg)', textTransform: 'uppercase', color: 'var(--color-text-muted)', fontWeight: 500, marginBottom: 'var(--space-4)' }}>Contents</p>
        <ul style={{ listStyle: 'none' }}>
          {sections.map(id => (
            <li key={id}>
              <a href={`#${id}`} style={getLinkStyle(id)} aria-current={id === active ? 'true' : undefined}>
                {id.charAt(0).toUpperCase() + id.slice(1)}
              </a>
            </li>
          ))}
        </ul>
      </aside>
    )
  },
}

export const Locked: Story = {
  name: 'Locked (unlocked: false)',
  args: {
    sections: ['overview', 'research', 'design', 'outcomes', 'reflections'],
    unlocked: false,
  },
}
