import type { Meta, StoryObj } from '@storybook/react'
import SideNav from './SideNav'

/**
 * Side navigation provides in-page navigation for case study pages. Uses
 * IntersectionObserver to track which section is currently visible and updates
 * the active state accordingly — a scrollspy pattern.
 *
 * ## Design rationale
 * IntersectionObserver was chosen over scroll event listeners because it's
 * declarative, performant, and doesn't require debouncing. The observer fires
 * only when a section enters or leaves the viewport, not on every scroll tick.
 *
 * The left border as the active indicator connects Side navigation to a broader
 * cross-component visual language: CalloutCard, MetricCard, and PasswordGate all
 * use a red left or top accent bar to signal highlighted content.
 *
 * Hidden on tablet and mobile via the `.article-layout` grid collapse.
 *
 * ## State model
 * - Default: `--color-text-muted`, weight 400, `--color-border` left border
 * - Hover: `--color-text-mid`, weight 500, `--color-border-mid` left border
 * - Active: `--color-accent`, weight 500, `--color-accent` left border
 *
 * ## Tokens used
 * - Contents label: `--font-size-xs`, `--letter-spacing-lg`, uppercase, `--color-text-muted`, weight 500
 * - Link font size: `--font-size-base` (0.875rem / 14px)
 * - Default color: `--color-text-muted`
 * - Hover color: `--color-text-mid`
 * - Active color: `--color-accent`
 * - Default border: `--color-border`
 * - Hover border: `--color-border-mid`
 * - Active border: `--color-accent`
 */
const meta: Meta<typeof SideNav> = {
  title: 'Core Components/Navigation/Side',
  tags: ['autodocs'],
  component: SideNav,
  argTypes: {
    sections: {
      control: 'object',
      description: 'Array of section IDs matching the id attributes of page sections. Labels are auto-generated by capitalizing the first letter.',
    },
    unlocked: {
      control: 'boolean',
      description: 'When false, IntersectionObserver setup is deferred. Used when content is behind PasswordGate.',
    },
  },
}

export default meta
type Story = StoryObj<typeof SideNav>

export const Default: Story = {
  args: {
    sections: ['overview', 'research', 'design', 'outcomes', 'reflections'],
    unlocked: true,
  },
}
