// lib/knowledge/caseStudies/portfolioAssistant.ts
// The dedicated deep-dive on the Portfolio Assistant chatbot itself -
// distinct from thePortfolio.ts, which covers the broader site. Drawn
// directly from real, first-hand build work across this project's own
// sessions, not reconstructed from external documentation.

import type { CaseStudyDetail } from '../types'

export const PORTFOLIO_ASSISTANT_DETAIL: CaseStudyDetail = {
  slug: 'portfolio-assistant',

  outcome:
    'An AI interaction design curriculum applied to a real, shipped product, not a theoretical exercise: system prompt design, guardrails (a password-protection guardrail, a reduction-in-force disclosure guardrail, an interview confirm/deny guardrail, and a graduated three-step hostility ladder with a severity override), and confidence calibration. A real automated eval framework was built - it fetches the live system prompt, runs test cases against the production model, and grades with an independent judge model - scoring 12/15 on its first real run, with a retroactive first-attempt pass rate of 54% across 28 test scenarios, improving to 100% after iterative fixing. That framework found and fixed two genuine security-relevant regressions in guardrails that had been passing reliably for weeks, and closed the loop on a fabricated fact that had been quietly distorting responses. A production Dashboard was built from real conversation logs, including categorized guardrail-trigger tracking and a user feedback mechanism (thumbs up/down per response).\n\nThe backend uses native tool-calling, not text parsing, for two tools alongside every visible reply. The first is a private, seven-field working estimate: who is likely asking (recruiter, hiring manager, product manager, engineer, or unknown), a confidence level, what depth of answer the conversation needs, whether this is a natural point to suggest contacting Ali directly, a coarse fit verdict during job-description matching (strong, partial, no fit, or not applicable - deliberately not a numeric score), a pointer to a specific case study when one would add real depth, and a self-reported register (fast/direct versus exploratory) used to check the system\'s own consistency against its stated policy. The second tool retrieves a specific project\'s detail on demand, across all 12 real case studies, keeping the default prompt lean rather than loading every project\'s full depth every turn. A structured skills matrix was built specifically for job-description matching, with three explicit honesty tiers rather than a flat list: confident skills, skills with real but limited experience (each with its specific real context attached), and genuine gaps that the assistant is explicitly instructed never to claim. Prompt caching was added once the always-loaded prompt reached roughly 78,000 characters, cutting the cost of the repeated static portion by roughly 90% on cache hits, confirmed by real, checkable numbers from production logs, not just by configuring the feature and assuming it worked.',

  businessConstraint:
    'The assistant has an explicit business goal - increasing the likelihood a visitor takes an action toward inviting Ali to interview - and every feature decision is weighed against that goal specifically, not against what a general-purpose assistant would do. The clearest example: an uncertainty-communication banner, visually flagging hedged versus confident claims, was deliberately not built. A system that has to detect its own uncertainty reliably risks flagging a confident, correct answer as shaky, which does more damage to trust than giving no signal at all - a real, asymmetric risk. That was weighed directly against a different feature, a contact-suggestion signal, which was left entirely to the model\'s own judgment, because getting that one wrong costs almost nothing - the plain contact link still sits right there regardless. A job-description match percentage was proposed and explicitly declined for a related reason: a fake-precision number conflicts with the whole system\'s design philosophy of never overclaiming confidence. The fit-verdict field that replaced it - a plain, coarse category instead of a number - is the direct resolution of that same tension. The skills matrix carries the identical philosophy one step further: documented gaps are protected from ever being claimed, even when a pasted job description specifically asks for exactly that gap.',

  technicalConstraint:
    'Because the assistant reports structured signals through native tool calls, a single visitor turn is not always one API call - it can require a genuine multi-step loop: call the model, receive a tool call, run it, feed the result back, and call again, repeating until a real answer is produced or a capped iteration limit is hit. Several distinct, separately-diagnosed bugs came out of building this correctly. One model response discarded a complete, valid answer, because the code wrongly treated a particular API stop condition as meaning "no real answer exists yet," when it actually only meant "still waiting on a pending tool result" - found only once real per-iteration logging replaced guessing with direct evidence. Separately, the project-lookup tool\'s slug parameter was originally free text, and the model would sometimes construct a plausible-sounding slug from a project\'s title instead of copying the real one - fixed structurally by constraining the parameter to a closed list derived directly from the real project index, making an invalid slug impossible to submit rather than merely discouraged by instruction. A related bug caused the assistant to keep retrying a lookup after being told a project had no record, exhausting the iteration cap with no answer produced - fixed with both a stronger instruction and a separate, code-level backstop that escalates on any repeated attempt, since an instruction alone had already proven unreliable for a closely related problem earlier in the same project. A formatting rule explicitly warning against markdown - including a specific warning that longer responses were the highest-risk case - was still violated on exactly that kind of response, fixed by adding a concrete real failure as the example rather than further abstract wording. Prompt caching was implemented as a static, cacheable system block kept fully separate from a small, per-turn dynamic block, with the tool definitions cached as a prefix and a single sliding cache breakpoint on the growing conversation history - deliberately kept to three of Anthropic\'s hard four-breakpoint-per-request limit, verified both by a standalone simulation of a full four-iteration loop and by real cache-hit numbers read back from production.',

  doNotFabricate: [
    'The 54% to 100% first-attempt pass rate is the retroactive eval scoring across 28 test scenarios from this project\'s own testing batches - it is not a claim about live user satisfaction or real visitor outcomes, which are not yet measured at meaningful volume.',
    'The discarded-answer bug, the slug-mismatch bug, the retry-loop-exhaustion bug, and the markdown-formatting bug were four distinct, separately-diagnosed issues with four distinct root causes - never describe them as one bug or conflate their fixes.',
    'At least one real misdiagnosis happened during this work: content initially flagged as fabricated turned out to be genuine, already-documented material, caught only once directly challenged and checked against the actual source. This is part of the honest process and should never be omitted or smoothed over as if every fix worked on the first attempt.',
    'Prompt caching\'s roughly 90% cost reduction on cached tokens is Anthropic\'s own published rate for cache reads, not a project-specific total-dollar-savings figure, which was not separately calculated.',
    'The four-cache-breakpoint-per-request limit is a real, documented constraint of the Anthropic API, not a self-imposed design choice - this system deliberately uses only three of the four available, leaving margin rather than running at the exact limit.',
    'All 12 real case study projects have migrated, complete four-lens detail as of the current state of this system - describe the knowledge base as complete, not partial or in-progress.',
  ],
}
