// lib/knowledge/caseStudies/thePortfolio.ts
// Unlike most other migrated projects, this content is drawn directly from
// real, first-hand work done across this project's own build sessions, not
// reconstructed from external documentation - the portfolio site (including
// this knowledge base structure itself) is the subject of the case study.
// Refreshed to reflect the full body of work, not just the first half of it -
// the previous version stopped before caching, several real production bugs,
// and the later additions to the audience-estimation tool call.

import type { CaseStudyDetail } from '../types'

export const THE_PORTFOLIO_DETAIL: CaseStudyDetail = {
  slug: 'the-portfolio',

  outcome:
    'This site itself, including the Portfolio Assistant chatbot, treated as a live, ongoing product rather than a finished artifact. A real automated eval framework was built (fetches the live system prompt, runs test cases against the production model, grades with an independent judge model) - its first real run scored 12/15, and the retroactive first-attempt pass rate across 28 test scenarios was 54%, improving to 100% after iterative fixing. That framework found and fixed two genuine security-relevant regressions in production guardrails that had been passing reliably for weeks, and closed the loop on a fabricated fact that had been quietly distorting responses. Deployment safety (branch protection, staged preview deployments) was set up and empirically tested, not just configured - a real direct push to the protected branch was attempted and confirmed rejected. A production Dashboard was built from real conversation logs, including categorized guardrail-trigger tracking and a user feedback mechanism.\n\nBeyond that first pass: the assistant now carries a genuine multi-step tool-calling loop with two tools, not one - a private audience/fit-tracking signal and an on-demand case-study lookup that retrieves a specific project\'s detail only when needed, across all 12 real projects, not a handful. The audience signal itself grew from four fields to seven, adding a fit-verdict category (a deliberately coarse strong/partial/no-fit read, chosen specifically instead of a numeric match percentage to avoid false precision), a case-study pointer the model can set to redirect a visitor to deeper material, and a register-consistency check comparing what tone the system said it would use against what it actually used. A structured skills matrix was built with three explicit honesty tiers - confident, light-with-context, and genuine gaps that are never to be claimed - specifically to make job-description matching precise rather than generic. Prompt caching was added once the always-loaded prompt reached roughly 78,000 characters: a static, cacheable system block separated from a small per-turn dynamic block, the tool definitions cached as a prefix, and a single sliding cache breakpoint on the growing message history, kept under Anthropic\'s hard four-breakpoint-per-request limit by design, verified both by a standalone runtime simulation across a full four-iteration loop and by real, checkable cache-hit numbers from production logs.',

  businessConstraint:
    'The chatbot has an explicit business goal - increasing the likelihood a visitor takes an action toward inviting Ali to interview - and every feature decision is weighed against that goal, not against "what would a general-purpose assistant do." Concrete example: an uncertainty-communication banner (flagging hedged vs. confident claims visually) was deliberately not built, because a system that has to detect its own uncertainty reliably risks flagging a confident, correct answer as shaky, which does more harm to trust than no signal at all - contrasted directly against a different feature (a contact-suggestion signal) that was left to model judgment, because getting that one wrong costs almost nothing. A JD-match percentage score was explicitly proposed and declined for a related reason: a fake-precision number conflicts with the entire system\'s design philosophy around not overclaiming confidence - the fit-verdict field that replaced it (strong/partial/no-fit, a plain category) is the direct resolution of that same tension. The skills matrix carries the identical philosophy one level further: gaps are listed and explicitly protected from being claimed, even when a pasted job description specifically asks for one of them.',

  technicalConstraint:
    'The chat backend uses native tool-calling (not text parsing) for structured signals alongside every visible reply, which required a genuine multi-step request loop, not a single API call - the model can call a tool, receive the result, and continue, repeating until it produces a real answer or hits a capped iteration limit. Several real, separately-diagnosed bugs came out of building this correctly, each with a distinct root cause rather than one generic "it broke" story: a model call once discarded a complete, valid answer because the code wrongly treated an API stop condition as meaning "no real answer exists yet," when it actually only meant "still waiting on a pending tool result" - found only once real per-iteration logging replaced guessing with actual evidence. Separately, the lookup tool\'s project-slug parameter was originally free text, and the model would sometimes construct a plausible-sounding slug from a project\'s title instead of copying the real one verbatim - fixed structurally by constraining the parameter to a closed enum derived directly from the real project list, making an invalid slug impossible to submit rather than merely discouraged. A retry-loop bug caused the assistant to keep re-attempting a lookup after being told a project had no record, burning through the iteration cap with no answer produced - fixed with both a stronger instruction and a programmatic backstop that escalates on any repeat attempt, since an instruction alone had already proven unreliable for a closely related problem earlier in the same project. A formatting instruction explicitly warning against markdown, including a warning that longer responses were the highest-risk case, still got violated on exactly that kind of response - fixed by adding a concrete real failure as the example, following the same pattern that had already worked for other prompt fixes, rather than further abstract wording.',

  doNotFabricate: [
    'The 54% to 100% first-attempt pass rate is specific to the retroactive eval scoring across 28 test scenarios from the project\'s own testing batches - it is not a claim about live user satisfaction or real visitor outcomes, which are not yet measured at meaningful volume.',
    'The debugging process for the audience-sensing and case-study-lookup features involved at least one real misdiagnosis along the way (content initially flagged as fabricated turned out to be genuine, already-documented material) that was caught and corrected once checked against the actual source - this is part of the honest process, not something to omit or gloss over as if every fix was correct on the first attempt.',
    'Prompt caching reduces cost on cached-prefix tokens by roughly 90% per Anthropic\'s published pricing - this is a real, verified rate as of when it was checked, not a project-specific measurement of total dollar savings, which was not separately calculated.',
    'The four-cache-breakpoint-per-request limit is a real, documented constraint of the Anthropic API, not a self-imposed design choice - the system was deliberately built to use only three of the four available breakpoints, leaving margin rather than running at the exact limit.',
    'The slug-mismatch, retry-loop, discarded-text, and markdown-formatting issues were each distinct bugs with distinct root causes, found and fixed separately across real testing, not one bug described four different ways.',
  ],
}
